apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: pangeo
  profile: circleci
  region: us-west-2
  updateAuthConfigmap: True

nodeGroups:
  - name: hub
    instanceType: m5.large
    allowSSH: true
    sshPublicKeyPath: "./pangeo-access-us-west-2.pub"
  - name: user-notebook
    instanceType: m5.2xlarge
    minSize: 0
    maxSize: 20
    desiredCapacity: 0
    allowSSH: true
    sshPublicKeyPath: "./pangeo-access-us-west-2.pub"
    ami: auto
    amiFamily: AmazonLinux2
    iam:
        withAddonPolicies:
            autoScaler: true
  - name: dask-worker
    instanceType: r5.2xlarge
    minSize: 0
    maxSize: 20
    desiredCapacity: 0
    allowSSH: true
    sshPublicKeyPath: "./pangeo-access-us-west-2.pub"
    ami: auto
    amiFamily: AmazonLinux2
    iam:
        withAddonPolicies:
            autoScaler: true
